project:
  type: website
resources:
  - CNAME

date: "last-modified"
date-format: "YYYY"

website:
  title: "Jack Krebsbach"
  description: "Jack Krebsbach is a PhD student studying Applied Mathematics and University of Colorado, Boulder"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: https://drive.google.com/file/d/1mr9Au7_SuzLEi7eNkITbSv6O1DwVldM-/view?usp=sharing
        text: My CV
  page-footer:
     left: "© <span id='current-year'></span> Jack Krebsbach"
  open-graph: true

format:
  html:
    theme:
      - cosmo
      - custom.scss
    toc: true
    toc_depth: 3
    toc_float: true
    toc_smooth_scroll: true
    toc_highlight: true
    fig-align: center
    include-in-header:
      text: |
        <script>
        document.addEventListener('DOMContentLoaded', (event) => {
          document.getElementById('current-year').textContent = new Date().getFullYear();
        });
        </script>
